language: node_js
sudo: false
node_js:
  - 6
  - 4

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run lint && npm run cover

after_success:
  - cat ./coverage/lcov.info  | ./node_modules/coveralls/bin/coveralls.js
  - cat ./coverage/coverage-final.json | ./node_modules/codecov.io/bin/codecov.io.js
