language: node_js
sudo: false
node_js:
  - 5
  - '4.2.2'

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm test && npm run cover

after_success:
  - cat ./coverage/coverage-remapped.lcov  | ./node_modules/coveralls/bin/coveralls.js
  - cat ./coverage/coverage-remapped.json | ./node_modules/codecov.io/bin/codecov.io.js
